CSTART OF AS 14
      SUBROUTINE MTP(N, B, C, HIST, ROUTE, XPRINT)
C
C        ALGORITHM AS 14  APPL. STATIST. (1969) VOL.18, P.105
C
C        THIS SUBROUTINE ENABLES THE MINIMUM SPANNING TREE TO BE
C        DRAWN RAPIDLY WITHOUT HAVING TO SEARCH FOR END POINTS,
C        AND IS ESPECIALLY USEFUL WHEN N EXCEEDS 100. THE OUTPUT
C        OF SUBROUTINE PRTREE IS USED
C
      INTEGER B(N), HIST(N), ROUTE(N)
      REAL C(N)
      DO 10 I = 1, N
   10 HIST(I) = 0
      DO 20 I = 2, N
      J = B(I)
      HIST(J) = HIST(J) + 1
   20 CONTINUE
      ROUTE(1) = 1
      J = 1
      K = 1
C
C        ROUTE(J) IS THE CURRENT END POINT AND IF HIST(ROUTE(I))
C        IS NOT ZERO A FURTHER LINE CAN BE FOUND. HIST(I) MUST
C        BE NON-ZERO INITIALLY BECAUSE THE TREE IS CONNECTED
C
      DO 80 I = 2, N
   30 IF (HIST(K) .NE. 0) GOTO 40
      J = J - 1
      K = ROUTE(J)
      GOTO 30
   40 HIST(K) = HIST(K) - 1
      DO 50 M = 2, N
      IF (K .EQ. B(M)) GOTO 60
   50 CONTINUE
   60 CALL XPRINT(J, K, M, C(M))
      J = J + 1
      ROUTE(J) = M
      K = M
      B(M) = -B(M)
   80 CONTINUE
      DO 90 I = 2, N
   90 B(I) = IABS(B(I))
      RETURN
      END
CEND OF AS 14
